[tool.poetry]
name = "niaarm"
version = "0.1.0"
description = "Nature-inspired algorithms for Association Rule Mining"
authors = ["Iztok Fister, Jr. <iztok.fister1@um.si>", "Žiga Stupan <ziga.stupan1@student.um.si"]

[tool.poetry.dependencies]
python = "^3.6"
niapy = "*"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
