[tool.poetry]
name = "niaarm"
version = "0.1.0"
description = ""
authors = ["Iztok Fister Jr. <iztok.fister1@um.si"]

[tool.poetry.dependencies]
python = "^3.6"
niapy = "2.0.0rc18"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
